runtime: nodejs22

instance_class: F2

handlers:
- url: /
  static_files: dist/CHILD_FOLDER_PATH_TO_SPECIFIC_FILES/index.html
  upload: dist/FOLDER_PATH_TO_SPECIFIC_FILES/index.html

- url: /
  static_dir: dist/CHILD_FOLDER_PATH_TO_SPECIFIC_FILES